name: Deploy Firebase App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables from GitHub secrets
      run: |
        echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
        echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
        echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
        echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
        echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
        echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
        echo "MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}" >> $GITHUB_ENV

    - name: Replace Firebase config in index.html
      run: |
        sed -i "s|{{FIREBASE_API_KEY}}|$FIREBASE_API_KEY|g" index.html
        sed -i "s|{{FIREBASE_AUTH_DOMAIN}}|$FIREBASE_AUTH_DOMAIN|g" index.html
        sed -i "s|{{FIREBASE_DATABASE_URL}}|$FIREBASE_DATABASE_URL|g" index.html
        sed -i "s|{{FIREBASE_PROJECT_ID}}|$FIREBASE_PROJECT_ID|g" index.html
        sed -i "s|{{FIREBASE_STORAGE_BUCKET}}|$FIREBASE_STORAGE_BUCKET|g" index.html
        sed -i "s|{{FIREBASE_MESSAGING_SENDER_ID}}|$FIREBASE_MESSAGING_SENDER_ID|g" index.html
        sed -i "s|{{FIREBASE_APP_ID}}|$FIREBASE_APP_ID|g" index.html
        sed -i "s|{{MEASUREMENT_ID}}|$MEASUREMENT_ID|g" index.html
        
